// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NetPlan.Server.Data;

namespace NetPlan.Server.Migrations;

[DbContext(typeof(NetPlanDbContext))]
partial class NetPlanDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("NetPlan.Server.Models.ColumnDefinition", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("TEXT");

            b.Property<string>("FieldName")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.Property<bool>("IsEditable")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(true);

            b.Property<bool>("IsVisible")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(true);

            b.Property<int>("ProjectId")
                .HasColumnType("INTEGER");

            b.Property<int>("SortOrder")
                .HasColumnType("INTEGER");

            b.Property<string>("ViewName")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.Property<int>("Width")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(100);

            b.HasKey("Id");

            b.HasIndex("ProjectId");

            b.HasIndex("ProjectId", "ViewName", "SortOrder");

            b.ToTable("ColumnDefinitions");
        });

        modelBuilder.Entity("NetPlan.Server.Models.Project", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("ActualEndDate")
                .HasColumnType("TEXT");

            b.Property<string>("ActualStartDate")
                .HasColumnType("TEXT");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .HasMaxLength(500)
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("TEXT");

            b.Property<string>("PlanEndDate")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("PlanStartDate")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("UpdatedAt")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int>("WorkingHoursPerDay")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(8);

            b.Property<int>("WorkdaysPerWeek")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(5);

            b.HasKey("Id");

            b.HasIndex("Code")
                .IsUnique();

            b.ToTable("Projects");
        });

        modelBuilder.Entity("NetPlan.Server.Models.Resource", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("ExtraData")
                .HasColumnType("TEXT");

            b.Property<decimal?>("HourlyCost")
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("TEXT");

            b.Property<string>("Notes")
                .HasMaxLength(500)
                .HasColumnType("TEXT");

            b.Property<int?>("ProjectId")
                .HasColumnType("INTEGER");

            b.Property<decimal>("Quantity")
                .HasColumnType("TEXT");

            b.Property<int>("Type")
                .HasColumnType("INTEGER");

            b.Property<string>("Unit")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("TEXT");

            b.Property<decimal>("UnitPrice")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("ProjectId");

            b.ToTable("Resources");
        });

        modelBuilder.Entity("NetPlan.Server.Models.ResourceAssignment", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Notes")
                .HasMaxLength(500)
                .HasColumnType("TEXT");

            b.Property<decimal>("Quantity")
                .HasColumnType("TEXT");

            b.Property<int>("ResourceId")
                .HasColumnType("INTEGER");

            b.Property<int>("TaskId")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("ResourceId");

            b.HasIndex("TaskId");

            b.ToTable("ResourceAssignments");
        });

        modelBuilder.Entity("NetPlan.Server.Models.TaskItem", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("ActualEndDate")
                .HasColumnType("TEXT");

            b.Property<int?>("ActualDuration")
                .HasColumnType("INTEGER");

            b.Property<string>("ActualStartDate")
                .HasColumnType("TEXT");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.Property<int>("CompletionPercentage")
                .HasColumnType("INTEGER");

            b.Property<string>("CreatedAt")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int?>("EarlyFinish")
                .HasColumnType("INTEGER");

            b.Property<int?>("EarlyStart")
                .HasColumnType("INTEGER");

            b.Property<string>("ExtraData")
                .HasColumnType("TEXT");

            b.Property<int?>("FreeFloat")
                .HasColumnType("INTEGER");

            b.Property<bool>("IsCritical")
                .HasColumnType("INTEGER");

            b.Property<bool>("IsManualSchedule")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(false);

            b.Property<bool>("IsMilestone")
                .HasColumnType("INTEGER");

            b.Property<int?>("LateFinish")
                .HasColumnType("INTEGER");

            b.Property<int?>("LateStart")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("TEXT");

            b.Property<string>("Notes")
                .HasMaxLength(500)
                .HasColumnType("TEXT");

            b.Property<int>("OutlineLevel")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(1);

            b.Property<int?>("ParentTaskId")
                .HasColumnType("INTEGER");

            b.Property<int>("PlanDuration")
                .HasColumnType("INTEGER");

            b.Property<string>("PlanEndDate")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("PlanStartDate")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int>("ProjectId")
                .HasColumnType("INTEGER");

            b.Property<string>("ResponsiblePerson")
                .HasMaxLength(50)
                .HasColumnType("TEXT");

            b.Property<int>("SortOrder")
                .HasColumnType("INTEGER");

            b.Property<int?>("TotalFloat")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("ParentTaskId");

            b.HasIndex("ProjectId");

            b.HasIndex("ProjectId", "SortOrder");

            b.ToTable("Tasks");
        });

        modelBuilder.Entity("NetPlan.Server.Models.TaskRelation", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("Lag")
                .HasColumnType("INTEGER");

            b.Property<int>("PredecessorTaskId")
                .HasColumnType("INTEGER");

            b.Property<int>("ProjectId")
                .HasColumnType("INTEGER");

            b.Property<int>("SuccessorTaskId")
                .HasColumnType("INTEGER");

            b.Property<int>("Type")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(0);

            b.HasKey("Id");

            b.HasIndex("PredecessorTaskId");

            b.HasIndex("ProjectId");

            b.HasIndex("SuccessorTaskId");

            b.ToTable("TaskRelations");
        });

        modelBuilder.Entity("NetPlan.Server.Models.ColumnDefinition", b =>
        {
            b.HasOne("NetPlan.Server.Models.Project", "Project")
                .WithMany("ColumnDefinitions")
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Project");
        });

        modelBuilder.Entity("NetPlan.Server.Models.Resource", b =>
        {
            b.HasOne("NetPlan.Server.Models.Project", "Project")
                .WithMany("Resources")
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.SetNull);

            b.Navigation("Project");
        });

        modelBuilder.Entity("NetPlan.Server.Models.ResourceAssignment", b =>
        {
            b.HasOne("NetPlan.Server.Models.Resource", "Resource")
                .WithMany("Assignments")
                .HasForeignKey("ResourceId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("NetPlan.Server.Models.TaskItem", "Task")
                .WithMany("ResourceAssignments")
                .HasForeignKey("TaskId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Resource");
            b.Navigation("Task");
        });

        modelBuilder.Entity("NetPlan.Server.Models.TaskItem", b =>
        {
            b.HasOne("NetPlan.Server.Models.TaskItem", "ParentTask")
                .WithMany("SubTasks")
                .HasForeignKey("ParentTaskId")
                .OnDelete(DeleteBehavior.Restrict);

            b.HasOne("NetPlan.Server.Models.Project", "Project")
                .WithMany("Tasks")
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("ParentTask");
            b.Navigation("Project");
        });

        modelBuilder.Entity("NetPlan.Server.Models.TaskRelation", b =>
        {
            b.HasOne("NetPlan.Server.Models.Project", "Project")
                .WithMany()
                .HasForeignKey("ProjectId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("NetPlan.Server.Models.TaskItem", "PredecessorTask")
                .WithMany("Successors")
                .HasForeignKey("PredecessorTaskId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("NetPlan.Server.Models.TaskItem", "SuccessorTask")
                .WithMany("Predecessors")
                .HasForeignKey("SuccessorTaskId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("PredecessorTask");
            b.Navigation("Project");
            b.Navigation("SuccessorTask");
        });

        modelBuilder.Entity("NetPlan.Server.Models.Project", b =>
        {
            b.Navigation("ColumnDefinitions");
            b.Navigation("Resources");
            b.Navigation("Tasks");
        });

        modelBuilder.Entity("NetPlan.Server.Models.Resource", b =>
        {
            b.Navigation("Assignments");
        });

        modelBuilder.Entity("NetPlan.Server.Models.TaskItem", b =>
        {
            b.Navigation("Predecessors");
            b.Navigation("ResourceAssignments");
            b.Navigation("SubTasks");
            b.Navigation("Successors");
        });
#pragma warning restore 612, 618
    }
}
