// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GanttReady.Server.Data;

#nullable disable

namespace GanttReady.Server.Migrations
{
    [DbContext(typeof(NetPlanDbContext))]
    [Migration("20260531080336_AddBaselineSupport")]
    partial class AddBaselineSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GanttReady.Server.Models.Baseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.ToTable("Baselines");
                });

            modelBuilder.Entity("GanttReady.Server.Models.BaselineTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaselineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlanEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaselineId");

                    b.ToTable("BaselineTasks");
                });

            modelBuilder.Entity("GanttReady.Server.Models.ColumnDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ViewName", "SortOrder");

                    b.ToTable("ColumnDefinitions");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkDayBits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkdaysPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingHoursPerDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GanttReady.Server.Models.ProjectHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Date")
                        .IsUnique();

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HourlyCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("GanttReady.Server.Models.ResourceAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TaskId");

                    b.ToTable("ResourceAssignments");
                });

            modelBuilder.Entity("GanttReady.Server.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ActualDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EarlyFinish")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EarlyStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FreeFloat")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMilestone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LateFinish")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LateStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutlineLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlanEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlanStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalFloat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("GanttReady.Server.Models.TaskRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PredecessorTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessorTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PredecessorTaskId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SuccessorTaskId");

                    b.ToTable("TaskRelations");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Baseline", b =>
                {
                    b.HasOne("GanttReady.Server.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GanttReady.Server.Models.BaselineTask", b =>
                {
                    b.HasOne("GanttReady.Server.Models.Baseline", "Baseline")
                        .WithMany("Tasks")
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baseline");
                });

            modelBuilder.Entity("GanttReady.Server.Models.ColumnDefinition", b =>
                {
                    b.HasOne("GanttReady.Server.Models.Project", "Project")
                        .WithMany("ColumnDefinitions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GanttReady.Server.Models.ProjectHoliday", b =>
                {
                    b.HasOne("GanttReady.Server.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Resource", b =>
                {
                    b.HasOne("GanttReady.Server.Models.Project", "Project")
                        .WithMany("Resources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GanttReady.Server.Models.ResourceAssignment", b =>
                {
                    b.HasOne("GanttReady.Server.Models.Resource", "Resource")
                        .WithMany("Assignments")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GanttReady.Server.Models.TaskItem", "Task")
                        .WithMany("ResourceAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GanttReady.Server.Models.TaskItem", b =>
                {
                    b.HasOne("GanttReady.Server.Models.TaskItem", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GanttReady.Server.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTask");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GanttReady.Server.Models.TaskRelation", b =>
                {
                    b.HasOne("GanttReady.Server.Models.TaskItem", "PredecessorTask")
                        .WithMany("Successors")
                        .HasForeignKey("PredecessorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GanttReady.Server.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GanttReady.Server.Models.TaskItem", "SuccessorTask")
                        .WithMany("Predecessors")
                        .HasForeignKey("SuccessorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PredecessorTask");

                    b.Navigation("Project");

                    b.Navigation("SuccessorTask");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Baseline", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Project", b =>
                {
                    b.Navigation("ColumnDefinitions");

                    b.Navigation("Resources");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GanttReady.Server.Models.Resource", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("GanttReady.Server.Models.TaskItem", b =>
                {
                    b.Navigation("Predecessors");

                    b.Navigation("ResourceAssignments");

                    b.Navigation("SubTasks");

                    b.Navigation("Successors");
                });
#pragma warning restore 612, 618
        }
    }
}
